version: '3'

services:
  # Service for the Python application
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    network_mode: "host"

  # Service for PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: starchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    network_mode: "host"

  # Service for Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    network_mode: "host"
