version: '3'

services:
  # Service for the Python application
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  # Service for PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: starchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql

  # Service for Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
