# Generated by Django 5.1 on 2024-08-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starchat', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
