# Generated by Django 5.1 on 2024-08-21 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starchat', '0003_comment_is_banned_post_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starchat.comment'),
        ),
    ]
